package ernest;

import javax.vecmath.Vector3f;

import imos.IAct;

import org.w3c.dom.Element;

import spas.IObservation;
import spas.IPlace;
import spas.IStimulation;
import spas.LocalSpaceMemory;
import spas.Observation;
import spas.Spas;
import spas.Stimulation;
import utils.ErnestUtils;

/**
 * Implement Ernest 11.0's sensorimotor system.
 * @author ogeorgeon
 */
public class SpatialSensorimotorSystem  extends BinarySensorymotorSystem
{
	/** The impulsion for translation */
	public final static float TRANSLATION_IMPULSION = .10f; // .10f; // .15f
	/** The impulsion for rotation */
	final static float ROTATION_IMPULSION = 0.123f;// .123f;//(float)Math.toRadians(7f); // degrees   . 5.5f
	/** The minimum speed before starting a new interaction */
	public final static float MINIMUM_SPEED = 0.05f;// .05f
	/** The delay when to measure the acceleration produced by the impulsion */
	public final static int IMPULSE_DELAY = 1;
	/** The delay when to consider an interaction succesfully enacted */
	public final static int INTERACTION_ONGOING = 3;
	
	/** The observation generated by the spatial system */
	private IObservation m_observation = null;
	
	/** The primitive act being enacted */
	//private IAct m_primitiveAct = null;
	
	private int m_interactionTimer = 0;
	private IObservation m_initialObservation = new Observation();
	private String m_expectedInstantaneousFeedback = "";
	
	/** The place of the last interaction */
	IPlace m_interactionPlace = null;

	public int[] update(int[][] stimuli) 
	{
		IObservation newObservation  = new Observation();
		
		//IAct primitiveAct = null;
		if (m_observation != null)
			newObservation.setPrimitiveAct(m_observation.getPrimitiveAct());
			//primitiveAct = m_observation.getPrimitiveAct();

		m_interactionTimer++;
		
		int primitiveSchema[] = new int[2];
		newObservation.setGustatoryValue(stimuli[0][8]); 
		newObservation.setKinematicValue(stimuli[1][8]);
		float translationx = (float) stimuli[2][8] / Ernest.INT_FACTOR; 
		float translationy = (float) stimuli[3][8] / Ernest.INT_FACTOR;
		float rotation = (float) stimuli[4][8] / Ernest.INT_FACTOR;
		//float speed = (float) stimuli[5][8] / Ernest.INT_FACTOR;
		int cognitiveMode = stimuli[6][8];
		
		newObservation.setTranslation(new Vector3f(translationx, translationy, 0));
		newObservation.setRotation(rotation);

		// Touch =====
		
		for (int i = 0; i < 9; i++)
			newObservation.setTactileStimuli(i, stimuli[i][9]);

    	// The Visual observation.
		
		for (int i = 0; i < Ernest.RESOLUTION_RETINA; i++)
		{
			newObservation.setVisualStimuli(i,stimuli[i][1] * 65536 + stimuli[i][2] * 256 + stimuli[i][3]);
			//float angle = (float) (- 11 * Math.PI/24 + i * Math.PI/12); 
			//Vector3f pos = new Vector3f((float) Math.cos(angle) * stimuli[i][0] / Ernest.INT_FACTOR, (float) Math.sin(angle) * stimuli[i][0] / Ernest.INT_FACTOR, 0);
			//m_visualStimulations[i].setPosition(pos);
		}
    	//sense(stimuli);
    	
		// The spatial observation ==========================================
		
		m_spas.step(m_interactionPlace, newObservation);
		
    	// The dynamic observation ==========================================
		
		boolean endInteraction = false;
		if (m_observation != null )
			endInteraction = dynamicFeedback(m_observation, newObservation);

    	// Memorize the initial observation.

		if (m_interactionTimer == IMPULSE_DELAY) // The acceleration is observed with a delay.
    		m_initialObservation = newObservation;
    		
		//m_observation = newObservation;

    	primitiveSchema[0] = 0;
    	primitiveSchema[1] = 0;
    	
    	// Trigger a new cognitive loop when the previous interaction has ended =============
    	
    	if (endInteraction && cognitiveMode > 0)
        {
        	m_spas.count(); // Tick the clock of persistence memory
    		IAct newPrimitiveAct = null;

        	
    		m_interactionTimer = 0;
    		        	
    		IAct enactedPrimitiveAct = null;
 
    		if (m_tracer != null)
    		{
                m_tracer.startNewEvent(m_imos.getCounter());
    			m_tracer.addEventElement("clock", m_imos.getCounter() + "");
    		}                

    		// If the intended act was null (during the first cycle), then the enacted act is null.

    		// Compute the enacted act == 
    		
    		if (newObservation.getPrimitiveAct() != null)
    		{
    			enactedPrimitiveAct = m_imos.addInteraction(newObservation.getPrimitiveAct().getSchema().getLabel(), newObservation.getStimuli(), newObservation.getSatisfaction());

    			if (m_tracer != null) 
    				m_tracer.addEventElement("primitive_enacted_schema", newObservation.getPrimitiveAct().getSchema().getLabel());
    		}
    		
    		// Let Ernest decide for the next primitive schema to enact =========================
    		
    		newPrimitiveAct = m_imos.step(enactedPrimitiveAct);
    		newObservation.setPrimitiveAct(newPrimitiveAct);
    		
    		primitiveSchema[0] = newPrimitiveAct.getSchema().getLabel().toCharArray()[0];
    		
    		// Expected instantaneous feedback ==================================================
    		
    		if (newPrimitiveAct.getLabel().indexOf("-") >= 0)
    			m_expectedInstantaneousFeedback = "-";
    		else if (newPrimitiveAct.getLabel().indexOf("+") >= 0)
    			m_expectedInstantaneousFeedback = "+";
    		else if (newPrimitiveAct.getLabel().indexOf("_") >= 0)
    			m_expectedInstantaneousFeedback = "_";
    		else if (newPrimitiveAct.getLabel().indexOf("*") >= 0)
    			m_expectedInstantaneousFeedback = "*";
    		else
    			m_expectedInstantaneousFeedback = "";
    		
    		// Once the decision is made, compute the intensity.
    		
    		primitiveSchema[1] = impulsion(primitiveSchema[0]);
    		
    		// Trace the interaction

			int shape = Spas.SHAPE_TRIANGLE;
    		if (primitiveSchema[0] != '>')
    			shape = Spas.SHAPE_PIE;
    		float or = 0;
    		if (primitiveSchema[0] == '^')
    			or = (float)Math.PI;
    		if (m_imos.newIntention())
    		{
    			if (m_imos.compositeIntention())
    				m_interactionPlace = m_spas.addPlace(new Vector3f(), Spas.PLACE_COMPOSITE, shape); // Mark the place where the agent is standing.
    			else
    				m_interactionPlace = m_spas.addPlace(new Vector3f(), Spas.PLACE_PRIMITIVE, shape); // Mark the place where the agent is standing.
    			//m_spas.addPlace(m_observation.getPosition(), Spas.PLACE_FOCUS, Spas.SHAPE_CIRCLE); // Mark the place of focus.
    		}
    		else
    			m_interactionPlace = m_spas.addPlace(new Vector3f(), Spas.PLACE_INTERMEDIARY, shape); // Mark the place where the agent is standing.    		
    		m_interactionPlace.setOrientation(or);

    		// Trace
    		if (m_tracer != null)
    		{
    			newObservation.trace(m_tracer);
    			m_spas.traceLocalSpace();
    		}
        }
    	
		m_observation = newObservation;

		return primitiveSchema;    		
	}
	
	/**
	 * Generate the instantaneous feedback that is computed from the instantaneous relative acceleration of the focus.
	 * @param previousObservation The observation made on the previous cycle.
	 * @param newObservation The current observation .
	 */
	//private void setInstantaneousFeedback(IObservation previousObservation, IObservation newObservation)
	private boolean dynamicFeedback(IObservation previousObservation, IObservation newObservation)
	{
		String instantaneousFeedback = "";
		IAct primitiveAct = previousObservation.getPrimitiveAct();
		
		// Compute the speed of tactile places TODO change this
		if (newObservation.getSpeed().z == .01f)
		{
			Vector3f relativeSpeed = new Vector3f(newObservation.getPosition());
			relativeSpeed.sub(previousObservation.getPosition());
			
			Vector3f rotationSpeed = new Vector3f(- newObservation.getPosition().y, newObservation.getPosition().x, 0); // Orthogonal to the position vector.
			rotationSpeed.normalize();
			rotationSpeed.scale(- newObservation.getRotation());
			relativeSpeed.add(rotationSpeed);
			newObservation.setSpeed(relativeSpeed);
		}
		
		Vector3f relativeAcceleration = new Vector3f(newObservation.getSpeed());
		relativeAcceleration.sub(previousObservation.getSpeed());
		
		if (newObservation.getAttractiveness() >= 0)
		{
			// Positive attractiveness
			// Move forward
			if (primitiveAct != null && primitiveAct.getSchema().getLabel().equals(">"))
			{
				if (relativeAcceleration.dot(newObservation.getPosition()) < 0 &&
					Math.abs(newObservation.getDirection()) < Math.PI/4)
					// Closer
					instantaneousFeedback = "+";
				else
					// Farther
					instantaneousFeedback = "-";
			}
			else
			{
				if (relativeAcceleration.x > 0)
					// More frontwards
					instantaneousFeedback = "+";
				else
					// More backward
					instantaneousFeedback = "-";
			}
		}
		else
		{
			// Negative attractiveness (repulsion)
			
			if (previousObservation.getAttractiveness() >= 0)
				// A wall appeared with a part of it in front of Ernest
				instantaneousFeedback = "*";		
			else 
			{
				// already in front of a wall.
				if (primitiveAct != null && primitiveAct.getSchema().getLabel().equals(">"))
				{
					if (relativeAcceleration.dot(newObservation.getPosition()) <= 0)
						// Closer
						instantaneousFeedback = "*";
					else
						// Farther
						instantaneousFeedback = "_";
				}
				else
				{
					if (relativeAcceleration.x > 0)
						// More to front
						instantaneousFeedback = "*";
					else
						// More to the side
						instantaneousFeedback = "_";
				}
			}
		}	
		
		newObservation.setInstantaneousFeedback(instantaneousFeedback);
//	}
//	
//	/**
//	 * Generate the dynamic stimuli from the impact in the local space memory.
//	 * The stimuli come from: 
//	 * - The kinematic feature.
//	 * - The variation in attractiveness and in direction of the object of interest. 
//	 * @param act The enacted act.
//	 */
//	private boolean setFinalFeedback(IObservation previousObservation, IObservation newObservation)
//	{
		boolean endInteraction = false;
		
		int   newAttractiveness = newObservation.getAttractiveness();
		float newDirection = newObservation.getDirection();
		
		String finalFeedback = "";
		
		float minFovea =  - (float)Math.PI / 4 + 0.01f;
		float maxFovea =    (float)Math.PI / 4 - 0.01f;
		
		// Incorrect ending
		// If the initial instantaneous feedback is not that expected then the interaction is ended.
		if (m_interactionTimer >= INTERACTION_ONGOING && !m_expectedInstantaneousFeedback.equals(m_initialObservation.getInstantaneousFeedback()))
			endInteraction = true;
		
		// Correct ending
		// If the current instantaneous feedback is no longer correct
		if (m_interactionTimer > INTERACTION_ONGOING )
		{
			if (primitiveAct != null && primitiveAct.getSchema().getLabel().equals(">"))
			// Move forward correct ending conditions
			{
				if (newObservation.getPosition().dot(newObservation.getSpeed()) > 0 ||
					Math.abs(newObservation.getDirection()) > Math.PI/4)
					// getting away
					endInteraction = true;
				else if (newObservation.getSpeed().length() < MINIMUM_SPEED)
					// stopped
					endInteraction = true;
			}
			else
			// Turn correct ending conditions
			{
				if (newObservation.getSpeed().x < 0 ||
						Math.abs(newObservation.getDirection()) > Math.PI/8)
					endInteraction = true;
				else if (newObservation.getSpeed().length() < MINIMUM_SPEED)
					// stopped
					endInteraction = true;
			}
		}
			
		
		// The final feedback is constructed from the initial instantaneous feedback and the ending condition.
		
		int satisfaction = 0;

		finalFeedback = m_initialObservation.getInstantaneousFeedback();

		if (newAttractiveness >= 0)
		{
			// Positive attractiveness
			{
				// Satisfaction
				if (finalFeedback.equals("-"))
					satisfaction = -100;
				if (finalFeedback.equals("+"))
					satisfaction = 20;

				// Direction
				if (!finalFeedback.equals(""))
				{
					if (newDirection <= minFovea)
						finalFeedback = "|" + finalFeedback;
					else if (newDirection >= maxFovea )
						finalFeedback = finalFeedback + "|";
				}		
			}
		}
		else
		{
			// Negative attractiveness (repulsion)
			// Satisfaction
			if (finalFeedback.equals("*"))
				satisfaction = -100;
			if (finalFeedback.equals("_"))
				satisfaction = 20;
			
			// Direction
			if (!finalFeedback.equals(""))
			{
				if (newDirection < -0.1f ) 
					finalFeedback = "|" + finalFeedback;
				else if (newDirection > 0.1f )
					finalFeedback = finalFeedback + "|";
			}		
		}
		
		// Gustatory
		
		if (newObservation.getGustatoryValue() != Ernest.STIMULATION_GUSTATORY_NOTHING)
		{
			finalFeedback = "e";
			satisfaction = 100;
		}
		
		// Kinematic
		
		boolean status = (newObservation.getKinematicValue() != Ernest.STIMULATION_KINEMATIC_BUMP);
		
		newObservation.setStimuli((status ? " " : "w") + finalFeedback);

		if (primitiveAct != null && primitiveAct.getSchema().getLabel().equals(">"))
			satisfaction = satisfaction + (status ? 20 : -100);
		else
			satisfaction = satisfaction + (status ? -10 : -20);
		
		newObservation.setSatisfaction(satisfaction);

		newObservation.setVisualFeedback(finalFeedback);
		
		return endInteraction;
	}
	
	
	
//	public void sense(int[][] stimuli)
//	{
//		// Vision =====
//		
//		m_visualStimulations = new Stimulation[Ernest.RESOLUTION_RETINA];
//		for (int i = 0; i < Ernest.RESOLUTION_RETINA; i++)
//		{
//			m_visualStimulations[i] = m_spas.addStimulation(Ernest.MODALITY_VISUAL, stimuli[i][1] * 65536 + stimuli[i][2] * 256 + stimuli[i][3]);
//			float angle = (float) (- 11 * Math.PI/24 + i * Math.PI/12); 
//			Vector3f pos = new Vector3f((float) Math.cos(angle) * stimuli[i][0] / Ernest.INT_FACTOR, (float) Math.sin(angle) * stimuli[i][0] / Ernest.INT_FACTOR, 0);
//			m_visualStimulations[i].setPosition(pos);
//		}
//		
//	}
	
	public int impulsion(int intentionSchema) 
	{
		int impulsion = 0;
		
		if (intentionSchema == '>')
		{
			impulsion = (int)(TRANSLATION_IMPULSION * Ernest.INT_FACTOR);
//			if (m_observation.getDistance() < .5f)
//				impulsion = (int)(TRANSLATION_IMPULSION * Ernest.INT_FACTOR * .5f);
//			if (m_observation.getDistance() < 1.1f)
//				impulsion = (int)(TRANSLATION_IMPULSION * Ernest.INT_FACTOR * m_observation.getDistance());
//			else
//				impulsion = (int)(TRANSLATION_IMPULSION * Ernest.INT_FACTOR * 1.1f);
		}
		if (intentionSchema == '^' || intentionSchema == 'v' )
		{ 
			impulsion = (int)(ROTATION_IMPULSION * Ernest.INT_FACTOR);
//			if (Math.abs(m_observation.getDirection()) > Math.PI/8)
//				impulsion = (int)(ROTATION_IMPULSION * Ernest.INT_FACTOR * Math.abs(m_observation.getDirection()) / (Math.PI/4));
//			if (impulsion > 2 * ROTATION_IMPULSION * Ernest.INT_FACTOR)
//				impulsion = (int)(2 * ROTATION_IMPULSION * Ernest.INT_FACTOR);
			
			//return (int)(Math.abs(m_observation.getPlace().getDirection()) * 1000);
		}
		return impulsion;
	}
}